[pytest]
testpaths = 
    tests

addopts = 
    -ra 
    -q 
    --cov=src/kubeflow_nb/pipeline/scripts
    --cov=src/client/api 
    --cov-report=term-missing
    --ignore=kubeflow
    --ignore=tests
    
markers =
    kfp_components: mark kfp unit tests.
    api: mark api unit tests.
    
   
