[pytest]
testpaths = 
    tests

addopts = 
    -ra 
    -q 
    --cov=src/kfp_outside/script 
    --cov=src/client/api 
    --cov-report=term-missing
    --ignore=kubeflow
    --ignore=tests/utils.py

markers =
    unittest: mark a test as a unit test.
    
env =
    MINIO_ENDPOINT=fake:9000
    MINIO_ACCESS_KEY=fake
    MINIO_SECRET_KEY=fake

[coverage:run]
omit =
    tests/utils.py                
