FIELD_DESCRIPTIONS = [
    {"name": "SK_ID_CURR", "type": "int", "desc": "Unique customer ID"},
    {
        "name": "NAME_CONTRACT_TYPE",
        "type": "str",
        "desc": "Type of loan contract (Cash loans, Revolving loans, etc.)",
    },
    {
        "name": "CODE_GENDER",
        "type": "str",
        "desc": "Gender of the client (e.g., 'M', 'F')",
    },
    {"name": "FLAG_OWN_CAR", "type": "str", "desc": "Does client own a car? ('Y'/'N')"},
    {
        "name": "FLAG_OWN_REALTY",
        "type": "str",
        "desc": "Does client own real estate? ('Y'/'N')",
    },
    {
        "name": "CNT_CHILDREN",
        "type": "int",
        "desc": "Number of children the client has",
    },
    {
        "name": "AMT_INCOME_TOTAL",
        "type": "float",
        "desc": "Client's total annual income",
    },
    {"name": "AMT_CREDIT", "type": "float", "desc": "Credit amount for the loan"},
    {"name": "AMT_ANNUITY", "type": "float", "desc": "Loan annuity payment amount"},
    {
        "name": "AMT_GOODS_PRICE",
        "type": "float",
        "desc": "Price of the goods for which the loan is given",
    },
    {
        "name": "NAME_TYPE_SUITE",
        "type": "str",
        "desc": "Who accompanied client when applying (Family, Spouse, Children, etc.)",
    },
    {
        "name": "NAME_INCOME_TYPE",
        "type": "str",
        "desc": "Source of income (Working, Pensioner, State servant, etc.)",
    },
    {"name": "NAME_EDUCATION_TYPE", "type": "str", "desc": "Education level"},
    {
        "name": "NAME_FAMILY_STATUS",
        "type": "str",
        "desc": "Family status (Single, Married, Separated, etc.)",
    },
    {
        "name": "NAME_HOUSING_TYPE",
        "type": "str",
        "desc": "Housing type (Own, Rented, Office, etc.)",
    },
    {
        "name": "REGION_POPULATION_RELATIVE",
        "type": "float",
        "desc": "Population relative in the region",
    },
    {
        "name": "DAYS_BIRTH",
        "type": "int",
        "desc": "Client's age in days (negative: days before application)",
    },
    {
        "name": "DAYS_EMPLOYED",
        "type": "float",
        "desc": "Number of days employed (negative: days before application)",
    },
    {
        "name": "DAYS_REGISTRATION",
        "type": "float",
        "desc": "Days since registration (negative: days before application)",
    },
    {
        "name": "DAYS_ID_PUBLISH",
        "type": "int",
        "desc": "Days since ID was published (negative: days before application)",
    },
    {"name": "OWN_CAR_AGE", "type": "int", "desc": "Age of client's car (years)"},
    {"name": "FLAG_MOBIL", "type": "int", "desc": "Has mobile phone (1 = yes, 0 = no)"},
    {
        "name": "FLAG_EMP_PHONE",
        "type": "int",
        "desc": "Has work phone (1 = yes, 0 = no)",
    },
    {
        "name": "FLAG_WORK_PHONE",
        "type": "int",
        "desc": "Has work phone (1 = yes, 0 = no)",
    },
    {
        "name": "FLAG_CONT_MOBILE",
        "type": "int",
        "desc": "Has contactable mobile phone (1 = yes, 0 = no)",
    },
    {"name": "FLAG_PHONE", "type": "int", "desc": "Has phone (1 = yes, 0 = no)"},
    {"name": "FLAG_EMAIL", "type": "int", "desc": "Has email (1 = yes, 0 = no)"},
    {"name": "OCCUPATION_TYPE", "type": "str", "desc": "Client's occupation type"},
    {"name": "CNT_FAM_MEMBERS", "type": "float", "desc": "Number of family members"},
    {
        "name": "REGION_RATING_CLIENT",
        "type": "int",
        "desc": "Client's region rating as provided by the client",
    },
    {
        "name": "REGION_RATING_CLIENT_W_CITY",
        "type": "int",
        "desc": "Client's region rating as provided by the client (with city)",
    },
    {
        "name": "WEEKDAY_APPR_PROCESS_START",
        "type": "str",
        "desc": "Weekday when application was submitted",
    },
    {
        "name": "HOUR_APPR_PROCESS_START",
        "type": "int",
        "desc": "Hour when application was submitted",
    },
    {
        "name": "REG_REGION_NOT_LIVE_REGION",
        "type": "int",
        "desc": "Flag: client not living in the region of registration",
    },
    {
        "name": "REG_REGION_NOT_WORK_REGION",
        "type": "int",
        "desc": "Flag: client not working in the region of registration",
    },
    {
        "name": "LIVE_REGION_NOT_WORK_REGION",
        "type": "int",
        "desc": "Flag: client living in the region not working in",
    },
    {
        "name": "REG_CITY_NOT_LIVE_CITY",
        "type": "int",
        "desc": "Flag: client not living in the city of registration",
    },
    {
        "name": "REG_CITY_NOT_WORK_CITY",
        "type": "int",
        "desc": "Flag: client not working in the city of registration",
    },
    {
        "name": "LIVE_CITY_NOT_WORK_CITY",
        "type": "int",
        "desc": "Flag: client living in city not working in",
    },
    {
        "name": "ORGANIZATION_TYPE",
        "type": "str",
        "desc": "Type of organization where client works",
    },
    {
        "name": "EXT_SOURCE_1",
        "type": "float",
        "desc": "External source 1 (score from external data)",
    },
    {
        "name": "EXT_SOURCE_2",
        "type": "float",
        "desc": "External source 2 (score from external data)",
    },
    {
        "name": "EXT_SOURCE_3",
        "type": "float",
        "desc": "External source 3 (score from external data)",
    },
    {
        "name": "APARTMENTS_AVG",
        "type": "float",
        "desc": "Average size of apartments in the building (normalized)",
    },
    {
        "name": "BASEMENTAREA_AVG",
        "type": "float",
        "desc": "Average size of basement in the building (normalized)",
    },
    {
        "name": "YEARS_BEGINEXPLUATATION_AVG",
        "type": "float",
        "desc": "Average years of building exploitation (normalized)",
    },
    {
        "name": "YEARS_BUILD_AVG",
        "type": "float",
        "desc": "Average years the building was built (normalized)",
    },
    {
        "name": "COMMONAREA_AVG",
        "type": "float",
        "desc": "Average common area size in building (normalized)",
    },
    {
        "name": "ELEVATORS_AVG",
        "type": "float",
        "desc": "Average number of elevators in building (normalized)",
    },
    {
        "name": "ENTRANCES_AVG",
        "type": "float",
        "desc": "Average number of entrances in building (normalized)",
    },
    {
        "name": "FLOORSMAX_AVG",
        "type": "float",
        "desc": "Average maximum floors in building (normalized)",
    },
    {
        "name": "FLOORSMIN_AVG",
        "type": "float",
        "desc": "Average minimum floors in building (normalized)",
    },
    {
        "name": "LANDAREA_AVG",
        "type": "float",
        "desc": "Average land area of the building (normalized)",
    },
    {
        "name": "LIVINGAPARTMENTS_AVG",
        "type": "float",
        "desc": "Average number of living apartments (normalized)",
    },
    {
        "name": "LIVINGAREA_AVG",
        "type": "float",
        "desc": "Average living area size (normalized)",
    },
    {
        "name": "NONLIVINGAPARTMENTS_AVG",
        "type": "float",
        "desc": "Average number of non-living apartments (normalized)",
    },
    {
        "name": "NONLIVINGAREA_AVG",
        "type": "float",
        "desc": "Average size of non-living area (normalized)",
    },
    {
        "name": "APARTMENTS_MODE",
        "type": "float",
        "desc": "Mode of apartment sizes in the building (normalized)",
    },
    {
        "name": "BASEMENTAREA_MODE",
        "type": "float",
        "desc": "Mode of basement area size (normalized)",
    },
    {
        "name": "YEARS_BEGINEXPLUATATION_MODE",
        "type": "float",
        "desc": "Mode of years of building exploitation (normalized)",
    },
    {
        "name": "YEARS_BUILD_MODE",
        "type": "float",
        "desc": "Mode of year the building was built (normalized)",
    },
    {
        "name": "COMMONAREA_MODE",
        "type": "float",
        "desc": "Mode of common area size (normalized)",
    },
    {
        "name": "ELEVATORS_MODE",
        "type": "float",
        "desc": "Mode of elevator numbers in building (normalized)",
    },
    {
        "name": "ENTRANCES_MODE",
        "type": "float",
        "desc": "Mode of number of entrances in building (normalized)",
    },
    {
        "name": "FLOORSMAX_MODE",
        "type": "float",
        "desc": "Mode of max floors in building (normalized)",
    },
    {
        "name": "FLOORSMIN_MODE",
        "type": "float",
        "desc": "Mode of min floors in building (normalized)",
    },
    {
        "name": "LANDAREA_MODE",
        "type": "float",
        "desc": "Mode of land area (normalized)",
    },
    {
        "name": "LIVINGAPARTMENTS_MODE",
        "type": "float",
        "desc": "Mode of living apartments (normalized)",
    },
    {
        "name": "LIVINGAREA_MODE",
        "type": "float",
        "desc": "Mode of living area size (normalized)",
    },
    {
        "name": "NONLIVINGAPARTMENTS_MODE",
        "type": "float",
        "desc": "Mode of non-living apartments (normalized)",
    },
    {
        "name": "NONLIVINGAREA_MODE",
        "type": "float",
        "desc": "Mode of non-living area (normalized)",
    },
    {
        "name": "APARTMENTS_MEDI",
        "type": "float",
        "desc": "Median of apartment sizes in building (normalized)",
    },
    {
        "name": "BASEMENTAREA_MEDI",
        "type": "float",
        "desc": "Median of basement area sizes (normalized)",
    },
    {
        "name": "YEARS_BEGINEXPLUATATION_MEDI",
        "type": "float",
        "desc": "Median years of building exploitation (normalized)",
    },
    {
        "name": "YEARS_BUILD_MEDI",
        "type": "float",
        "desc": "Median of year building built (normalized)",
    },
    {
        "name": "COMMONAREA_MEDI",
        "type": "float",
        "desc": "Median of common area size (normalized)",
    },
    {
        "name": "ELEVATORS_MEDI",
        "type": "float",
        "desc": "Median number of elevators in building (normalized)",
    },
    {
        "name": "ENTRANCES_MEDI",
        "type": "float",
        "desc": "Median number of entrances (normalized)",
    },
    {
        "name": "FLOORSMAX_MEDI",
        "type": "float",
        "desc": "Median of max floors in building (normalized)",
    },
    {
        "name": "FLOORSMIN_MEDI",
        "type": "float",
        "desc": "Median of min floors in building (normalized)",
    },
    {
        "name": "LANDAREA_MEDI",
        "type": "float",
        "desc": "Median of land area (normalized)",
    },
    {
        "name": "LIVINGAPARTMENTS_MEDI",
        "type": "float",
        "desc": "Median of living apartments (normalized)",
    },
    {
        "name": "LIVINGAREA_MEDI",
        "type": "float",
        "desc": "Median of living area size (normalized)",
    },
    {
        "name": "NONLIVINGAPARTMENTS_MEDI",
        "type": "float",
        "desc": "Median of non-living apartments (normalized)",
    },
    {
        "name": "NONLIVINGAREA_MEDI",
        "type": "float",
        "desc": "Median of non-living area (normalized)",
    },
    {
        "name": "FONDKAPREMONT_MODE",
        "type": "str",
        "desc": "Type of building fund (maintenance)",
    },
    {"name": "HOUSETYPE_MODE", "type": "float", "desc": "Type of house (normalized)"},
    {"name": "TOTALAREA_MODE", "type": "str", "desc": "Total area mode (str type)"},
    {
        "name": "WALLSMATERIAL_MODE",
        "type": "str",
        "desc": "Walls material of the house",
    },
    {
        "name": "EMERGENCYSTATE_MODE",
        "type": "float",
        "desc": "Emergency state of the building (normalized)",
    },
    {
        "name": "OBS_30_CNT_SOCIAL_CIRCLE",
        "type": "float",
        "desc": "Number of observation of 30 days social circle",
    },
    {
        "name": "DEF_30_CNT_SOCIAL_CIRCLE",
        "type": "float",
        "desc": "Number of default in 30 days social circle",
    },
    {
        "name": "OBS_60_CNT_SOCIAL_CIRCLE",
        "type": "float",
        "desc": "Number of observation of 60 days social circle",
    },
    {
        "name": "DEF_60_CNT_SOCIAL_CIRCLE",
        "type": "float",
        "desc": "Number of default in 60 days social circle",
    },
    {
        "name": "DAYS_LAST_PHONE_CHANGE",
        "type": "float",
        "desc": "Days since last phone change (negative: days before application)",
    },
    {"name": "FLAG_DOCUMENT_2", "type": "int", "desc": "Provided document 2"},
    {"name": "FLAG_DOCUMENT_3", "type": "int", "desc": "Provided document 3"},
    {"name": "FLAG_DOCUMENT_4", "type": "int", "desc": "Provided document 4"},
    {"name": "FLAG_DOCUMENT_5", "type": "int", "desc": "Provided document 5"},
    {"name": "FLAG_DOCUMENT_6", "type": "int", "desc": "Provided document 6"},
    {"name": "FLAG_DOCUMENT_7", "type": "int", "desc": "Provided document 7"},
    {"name": "FLAG_DOCUMENT_8", "type": "int", "desc": "Provided document 8"},
    {"name": "FLAG_DOCUMENT_9", "type": "int", "desc": "Provided document 9"},
    {"name": "FLAG_DOCUMENT_10", "type": "int", "desc": "Provided document 10"},
    {"name": "FLAG_DOCUMENT_11", "type": "int", "desc": "Provided document 11"},
    {"name": "FLAG_DOCUMENT_12", "type": "int", "desc": "Provided document 12"},
    {"name": "FLAG_DOCUMENT_13", "type": "int", "desc": "Provided document 13"},
    {"name": "FLAG_DOCUMENT_14", "type": "int", "desc": "Provided document 14"},
    {"name": "FLAG_DOCUMENT_15", "type": "int", "desc": "Provided document 15"},
    {"name": "FLAG_DOCUMENT_16", "type": "int", "desc": "Provided document 16"},
    {"name": "FLAG_DOCUMENT_17", "type": "int", "desc": "Provided document 17"},
    {"name": "FLAG_DOCUMENT_18", "type": "int", "desc": "Provided document 18"},
    {"name": "FLAG_DOCUMENT_19", "type": "int", "desc": "Provided document 19"},
    {"name": "FLAG_DOCUMENT_20", "type": "int", "desc": "Provided document 20"},
    {"name": "FLAG_DOCUMENT_21", "type": "int", "desc": "Provided document 21"},
    {
        "name": "AMT_REQ_CREDIT_BUREAU_HOUR",
        "type": "float",
        "desc": "Number of inquiries to credit bureau in last hour",
    },
    {
        "name": "AMT_REQ_CREDIT_BUREAU_DAY",
        "type": "float",
        "desc": "Number of inquiries to credit bureau in last day",
    },
    {
        "name": "AMT_REQ_CREDIT_BUREAU_WEEK",
        "type": "float",
        "desc": "Number of inquiries to credit bureau in last week",
    },
    {
        "name": "AMT_REQ_CREDIT_BUREAU_MON",
        "type": "float",
        "desc": "Number of inquiries to credit bureau in last month",
    },
    {
        "name": "AMT_REQ_CREDIT_BUREAU_QRT",
        "type": "float",
        "desc": "Number of inquiries to credit bureau in last quarter",
    },
    {
        "name": "AMT_REQ_CREDIT_BUREAU_YEAR",
        "type": "float",
        "desc": "Number of inquiries to credit bureau in last year",
    },
]
