FROM python:3.11.11-slim

RUN apt-get update && \
    apt-get install -y libgomp1 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./requirements_test.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

CMD ["/bin/bash"]
