FROM ghcr.io/kubeflow/kubeflow/notebook-servers/jupyter-scipy:sha-4a26c7b5e9575410613faf7df6735aa1883a2d24

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    DEBIAN_FRONTEND=noninteractive

WORKDIR /app

COPY kubeflow/notebook/requirements.txt ./requirements.txt

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt
