version: '3.8'

services:
  jenkins:
    image: microwave1005/custom-jenkins:latest
    platform: linux/amd64
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /etc/hosts:/etc/hosts:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.kube:/root/.kube:ro                      
      - ${HOME}/.config/gcloud:/root/.config/gcloud:ro    


volumes:
  jenkins_home:
